In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
thermal_stability = pd.read_csv("../data/Thermal_stability_Final1.csv", encoding="cp1252")
thermal_stability.head()

C:\Users\user\AppData\Local\Temp\ipykernel_6076\1199883940.py:1: DtypeWarning: Columns (0: Unnamed: 18, 1: Unnamed: 19, 2: Unnamed: 20, 3: Unnamed: 21, 4: Unnamed: 22, 5: Unnamed: 23, 6: Unnamed: 24, 7: Unnamed: 25, 8: Unnamed: 26) have mixed types. Specify dtype option on import or set low_memory=False.
  thermal_stability = pd.read_csv("../data/Thermal_stability_Final1.csv", encoding="cp1252")

,day or night,hour,Date/Time,Ch2_Speed_59m_E [m/s],Ch2_Speed_59m_E_SD [m/s],Ch6_Speed_22m_E [m/s],Ch6_Speed_22m_E_SD [m/s],Ch16_Temperature_59m_N [°C],Ch16_Temperature_59m_N_SD [°C],Ch15_Temperature_22m_N [°C],...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,...,NaN,NaN,M6171,Delta T,NaN,Shear,NaN,TI,NaN,NaN
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,...,Stable,26133,50%,26734,51%,28736,57%,32200,62%,NaN
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,...,Neutral,14495,28%,22003,42%,7774,15%,8250,16%,NaN
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,...,Unstable,11337,22%,3241,6%,14062,28%,11528,22%,NaN
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,...,NaN,51965,NaN,51978,NaN,50572,NaN,51978,NaN,NaN

In [24]:
thermal_stability.columns

Index(['day or night', 'hour', 'Date/Time', 'Ch2_Speed_59m_E [m/s]',
       'Ch2_Speed_59m_E_SD [m/s]', 'Ch6_Speed_22m_E [m/s]',
       'Ch6_Speed_22m_E_SD [m/s]', 'Ch16_Temperature_59m_N [°C]',
       'Ch16_Temperature_59m_N_SD [°C]', 'Ch15_Temperature_22m_N [°C]',
       'Ch15_Temperature_22m_N_SD [°C]', 'Ri', 'WS Bin', 'TI', 'Shear',
       'WS 120', 'stability', 'Delta T', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27'],
      dtype='str')

In [25]:
thermal_stability = thermal_stability.loc[
    :, ~thermal_stability.columns.str.contains("^Unnamed")
]

In [26]:
thermal_stability.columns

Index(['day or night', 'hour', 'Date/Time', 'Ch2_Speed_59m_E [m/s]',
       'Ch2_Speed_59m_E_SD [m/s]', 'Ch6_Speed_22m_E [m/s]',
       'Ch6_Speed_22m_E_SD [m/s]', 'Ch16_Temperature_59m_N [°C]',
       'Ch16_Temperature_59m_N_SD [°C]', 'Ch15_Temperature_22m_N [°C]',
       'Ch15_Temperature_22m_N_SD [°C]', 'Ri', 'WS Bin', 'TI', 'Shear',
       'WS 120', 'stability', 'Delta T'],
      dtype='str')

In [27]:
thermal_stability.head()

,day or night,hour,Date/Time,Ch2_Speed_59m_E [m/s],Ch2_Speed_59m_E_SD [m/s],Ch6_Speed_22m_E [m/s],Ch6_Speed_22m_E_SD [m/s],Ch16_Temperature_59m_N [°C],Ch16_Temperature_59m_N_SD [°C],Ch15_Temperature_22m_N [°C],Ch15_Temperature_22m_N_SD [°C],Ri,WS Bin,TI,Shear,WS 120,stability,Delta T
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,0.05,2.04,3.0,0.158503,0.096512,3.11,stable,0.405405
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,0.20,0.74,3.0,0.313112,0.093896,3.34,stable,0.162162
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,0.08,-0.19,3.5,0.145330,0.070780,3.49,unstable,-0.027027
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,0.05,0.22,3.5,0.154810,0.150416,3.74,stable,0.135135
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,0.21,0.34,4.0,0.152006,0.095996,3.98,stable,0.108108

In [28]:
thermal_stability.isna().sum()

day or night                      201
hour                              201
Date/Time                         201
Ch2_Speed_59m_E [m/s]             201
Ch2_Speed_59m_E_SD [m/s]          201
Ch6_Speed_22m_E [m/s]             204
Ch6_Speed_22m_E_SD [m/s]          204
Ch16_Temperature_59m_N [°C]       201
Ch16_Temperature_59m_N_SD [°C]    201
Ch15_Temperature_22m_N [°C]       201
Ch15_Temperature_22m_N_SD [°C]    201
Ri                                201
WS Bin                            201
TI                                201
Shear                             204
WS 120                            203
stability                         201
Delta T                           201
dtype: int64

In [29]:
thermal_stability.info()

<class 'pandas.DataFrame'>
RangeIndex: 52179 entries, 0 to 52178
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   day or night                    51978 non-null  str
 1   hour                            51978 non-null  float64
 2   Date/Time                       51978 non-null  str
 3   Ch2_Speed_59m_E [m/s]           51978 non-null  float64
 4   Ch2_Speed_59m_E_SD [m/s]        51978 non-null  float64
 5   Ch6_Speed_22m_E [m/s]           51975 non-null  float64
 6   Ch6_Speed_22m_E_SD [m/s]        51975 non-null  float64
 7   Ch16_Temperature_59m_N [°C]     51978 non-null  float64
 8   Ch16_Temperature_59m_N_SD [°C]  51978 non-null  float64
 9   Ch15_Temperature_22m_N [°C]     51978 non-null  float64
 10  Ch15_Temperature_22m_N_SD [°C]  51978 non-null  float64
 11  Ri                              51978 non-null  str
 12  WS Bin                          51978 non-null  float64
 13  TI                              51978 non-null  float64
 14  Shear                           51975 non-null  float64
 15  WS 120                          51976 non-null  float64
 16  stability                       51978 non-null  str
 17  Delta T                         51978 non-null  float64
dtypes: float64(14), str(4)
memory usage: 7.2 MB

In [30]:
thermal_stability.shape

(52179, 18)

In [31]:
thermal_stability.head()

,day or night,hour,Date/Time,Ch2_Speed_59m_E [m/s],Ch2_Speed_59m_E_SD [m/s],Ch6_Speed_22m_E [m/s],Ch6_Speed_22m_E_SD [m/s],Ch16_Temperature_59m_N [°C],Ch16_Temperature_59m_N_SD [°C],Ch15_Temperature_22m_N [°C],Ch15_Temperature_22m_N_SD [°C],Ri,WS Bin,TI,Shear,WS 120,stability,Delta T
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,0.05,2.04,3.0,0.158503,0.096512,3.11,stable,0.405405
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,0.20,0.74,3.0,0.313112,0.093896,3.34,stable,0.162162
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,0.08,-0.19,3.5,0.145330,0.070780,3.49,unstable,-0.027027
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,0.05,0.22,3.5,0.154810,0.150416,3.74,stable,0.135135
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,0.21,0.34,4.0,0.152006,0.095996,3.98,stable,0.108108

In [32]:
thermal_stability = thermal_stability.rename(columns={
    "Ch2_Speed_59m_E [m/s]": "ws59",
    "Ch2_Speed_59m_E_SD [m/s]": "ws59_sd",

    "Ch6_Speed_22m_E [m/s]": "ws22",
    "Ch6_Speed_22m_E_SD [m/s]": "ws22_sd",

    "Ch16_Temperature_59m_N [°C]": "temp59",
    "Ch16_Temperature_59m_N_SD [°C]": "temp59_sd",

    "Ch15_Temperature_22m_N [°C]": "temp22",
    "Ch15_Temperature_22m_N_SD [°C]": "temp22_sd",

    "Ri": "ri",
    "WS Bin": "ws_bin",
    "TI": "ti",
    "Shear": "shear",
    "WS 120": "ws120",
    "Delta T": "delta_t"
})

In [33]:
thermal_stability.head()

,day or night,hour,Date/Time,ws59,ws59_sd,ws22,ws22_sd,temp59,temp59_sd,temp22,temp22_sd,ri,ws_bin,ti,shear,ws120,stability,delta_t
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,0.05,2.04,3.0,0.158503,0.096512,3.11,stable,0.405405
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,0.20,0.74,3.0,0.313112,0.093896,3.34,stable,0.162162
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,0.08,-0.19,3.5,0.145330,0.070780,3.49,unstable,-0.027027
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,0.05,0.22,3.5,0.154810,0.150416,3.74,stable,0.135135
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,0.21,0.34,4.0,0.152006,0.095996,3.98,stable,0.108108

In [34]:
thermal_stability.isna().sum()

day or night    201
hour            201
Date/Time       201
ws59            201
ws59_sd         201
ws22            204
ws22_sd         204
temp59          201
temp59_sd       201
temp22          201
temp22_sd       201
ri              201
ws_bin          201
ti              201
shear           204
ws120           203
stability       201
delta_t         201
dtype: int64

In [35]:
thermal_stability = thermal_stability.dropna()

In [36]:
thermal_stability.isna().sum()

day or night    0
hour            0
Date/Time       0
ws59            0
ws59_sd         0
ws22            0
ws22_sd         0
temp59          0
temp59_sd       0
temp22          0
temp22_sd       0
ri              0
ws_bin          0
ti              0
shear           0
ws120           0
stability       0
delta_t         0
dtype: int64

In [37]:
thermal_stability.count()

day or night    51975
hour            51975
Date/Time       51975
ws59            51975
ws59_sd         51975
ws22            51975
ws22_sd         51975
temp59          51975
temp59_sd       51975
temp22          51975
temp22_sd       51975
ri              51975
ws_bin          51975
ti              51975
shear           51975
ws120           51975
stability       51975
delta_t         51975
dtype: int64

In [38]:
thermal_stability.head()

,day or night,hour,Date/Time,ws59,ws59_sd,ws22,ws22_sd,temp59,temp59_sd,temp22,temp22_sd,ri,ws_bin,ti,shear,ws120,stability,delta_t
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,0.05,2.04,3.0,0.158503,0.096512,3.11,stable,0.405405
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,0.20,0.74,3.0,0.313112,0.093896,3.34,stable,0.162162
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,0.08,-0.19,3.5,0.145330,0.070780,3.49,unstable,-0.027027
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,0.05,0.22,3.5,0.154810,0.150416,3.74,stable,0.135135
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,0.21,0.34,4.0,0.152006,0.095996,3.98,stable,0.108108

In [39]:
thermal_stability["py_delta_t"] = ((thermal_stability["temp59"] - thermal_stability["temp22"])/(59 - 22)) * 100

In [40]:
thermal_stability.head()

,day or night,hour,Date/Time,ws59,ws59_sd,ws22,ws22_sd,temp59,temp59_sd,temp22,temp22_sd,ri,ws_bin,ti,shear,ws120,stability,delta_t,py_delta_t
0,Day,16.0,06-05-2019 16:20,2.940,0.466,2.673,0.495,22.27,0.02,22.12,0.05,2.04,3.0,0.158503,0.096512,3.11,stable,0.405405,0.405405
1,Day,16.0,06-05-2019 16:30,3.165,0.991,2.885,0.826,22.42,0.13,22.36,0.20,0.74,3.0,0.313112,0.093896,3.34,stable,0.162162,0.162162
2,Day,16.0,06-05-2019 16:40,3.351,0.487,3.125,0.628,22.36,0.05,22.37,0.08,-0.19,3.5,0.145330,0.070780,3.49,unstable,-0.027027,-0.027027
3,Day,16.0,06-05-2019 16:50,3.430,0.531,2.957,0.539,22.10,0.04,22.05,0.05,0.22,3.5,0.154810,0.150416,3.74,stable,0.135135,0.135135
4,Day,17.0,06-05-2019 17:00,3.763,0.572,3.423,0.671,21.79,0.20,21.75,0.21,0.34,4.0,0.152006,0.095996,3.98,stable,0.108108,0.108108

In [41]:
thermal_stability[["delta_t","py_delta_t"]].head()

    delta_t  py_delta_t
0  0.405405    0.405405
1  0.162162    0.162162
2 -0.027027   -0.027027
3  0.135135    0.135135
4  0.108108    0.108108

In [42]:
def calculate_delta_t(t1, t2):
    return ((t1-t2)/(59-22)) * 100

thermal_stability["fun"] = calculate_delta_t(thermal_stability["temp59"], thermal_stability["temp22"])

In [43]:
print(thermal_stability.head())

  day or night  hour         Date/Time   ws59  ws59_sd   ws22  ws22_sd  \
0          Day  16.0  06-05-2019 16:20  2.940    0.466  2.673    0.495
1          Day  16.0  06-05-2019 16:30  3.165    0.991  2.885    0.826
2          Day  16.0  06-05-2019 16:40  3.351    0.487  3.125    0.628
3          Day  16.0  06-05-2019 16:50  3.430    0.531  2.957    0.539
4          Day  17.0  06-05-2019 17:00  3.763    0.572  3.423    0.671

   temp59  temp59_sd  temp22  temp22_sd     ri  ws_bin        ti     shear  \
0   22.27       0.02   22.12       0.05   2.04     3.0  0.158503  0.096512
1   22.42       0.13   22.36       0.20   0.74     3.0  0.313112  0.093896
2   22.36       0.05   22.37       0.08  -0.19     3.5  0.145330  0.070780
3   22.10       0.04   22.05       0.05   0.22     3.5  0.154810  0.150416
4   21.79       0.20   21.75       0.21   0.34     4.0  0.152006  0.095996

   ws120 stability   delta_t  py_delta_t       fun
0   3.11    stable  0.405405    0.405405  0.405405
1   3.34    stable  0.162162    0.162162  0.162162
2   3.49  unstable -0.027027   -0.027027 -0.027027
3   3.74    stable  0.135135    0.135135  0.135135
4   3.98    stable  0.108108    0.108108  0.108108